name: Coursework
on: push

jobs:
  build:
    name: Course work Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge course-work
          docker pull mongo
          docker run -d --name mongo-dbserver --network course-work mongo
      - name: Build with Maven
        run: mvn package
      - name: Build Docker Image
        run: docker build -t course_work .
      - name: Run image
        run: docker run --network course-work --name cwcontainer course_work
      - name: view logs
        run: docker logs cwcontainer

